### ISSUE TITLE
Consumer key and Consumer secret

### ISSUE THREAD

**Issue by winbotscript** [twitterdev/bot-profile-append#1]
Hi there, help me please cause i can't get consumer key and consumer secret after i register developer tweeter with an issue like this: 

**Consumer Keys
On 01/12/2021 your consumer keys will no longer be visible.
To increase security, make sure to save your keys before they're permanently hidden. Select View keys below and save them somewhere safe.**

Regards,

WinBot

**Comment by andypiper** [comment]
You can regenerate your keys on the Developer Dashboard, and put the new values somewhere safe (such as a password manager). Closing this issue as it is not a code issue with this repository. Thanks!
